### ISSUE TITLE
tela em portugues e whatson studio

### ISSUE THREAD

**Issue by Felipeddn** [MagnoSantos/chatbot-api#2]
Estou configurando os requisitos para participar da primeira mentoria cody anywhere e verifiquei umas mudanças da versão em inglês da pagina para a versão em português, na versão inglês whatson assistent e em portugues whatson studio me deixou com certa dúvida, 
![image](https://user-images.githubusercontent.com/56466463/116122282-f116ae00-a697-11eb-9000-1727e036f550.png)
![image](https://user-images.githubusercontent.com/56466463/116122318-fd027000-a697-11eb-96f6-21c9ad22dbb8.png)
desejo saber se estou seguindo corretamente mesmo com essas diferenças de nomenclatura, muito obrigado!

**Comment by MagnoSantos** [comment]
Oi Felipe, obrigado pelo interesse e dedicação.

Na verdade são dois produtos diferentes:
1)	[Watson Studio](https://www.ibm.com/br-pt/cloud/watson-studio), de forma bem geral é uma plataforma para Data Science que se encontra dentro do IBM Cloud Pack for Data;
2)	No caso do [Watson Assistant](https://www.ibm.com/cloud/watson-assistant), é uma ferramenta para construção de assistentes virtuais como exposto no hands-on. O Passo a passo que mostramos deve ser feito nessa ferramenta.

Espero que tenha ficado claro, caso ainda reste dúvidas por favor não hesite.

Abraços!
